version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: notifserv_web
    command: bash start.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: notifserv_celery
    command: celery -A notifserv worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db