# Generated by Django 4.1.1 on 2022-09-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('operCode', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
                ('tz', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDatetime', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('fltr', models.CharField(max_length=50)),
                ('endDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDatetime', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('mailinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailinglist')),
            ],
        ),
    ]
