# Generated by Django 4.1.1 on 2022-09-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_enddatetime_mailinglist_expdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='taskId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
